version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    #depend_on:
    # - wordpress
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - /home/rchahban/simple_docker_nginx_html/public/html:/var/www/
    ports:
      - "443:443"
    restart: always
    container_name: nginx
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    env_file: .env
